name: cointopper
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bottom_navy_bar: ^5.5.0
  carousel_slider: ^2.3.1
  cupertino_icons: ^0.1.3
  device_preview: ^0.5.5
  fl_chart: ^0.12.2
  flutter_webview_plugin: ^0.3.11
  font_awesome_flutter: ^8.10.0
  hexcolor: ^1.0.6
  image_picker_saver: ^0.3.0
  infinite_scroll_pagination: ^2.3.0
  intl: ^0.16.1
  readmore: ^1.0.1
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  youtube_player_flutter: ^7.0.0+7



dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^1.2.5
  flutter_bloc: ^6.0.6
  http: ^0.12.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
#     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
